version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py wsgi:app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./selfsigned.key:/etc/ssl/private/selfsigned.key
    depends_on:
      - app