name: Deploy to server
run-name: Deploy to server
on:
  push:
    branches:
      - "dev"
    # workflow_run:
    # workflows: ["CI Test"]  
    # types:
    #   - completed

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/automation-teamwork
            git pull origin dev
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp  # hoặc restart docker/nginx 