name: Deploy to server

on:
  push:
    branches:
      - "dev"
    # workflow_run:
    # workflows: ["CI Test"]  
    # types:
    #   - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd automation-teamwork || git clone https://github.com/LuongTanTai200803/automation-teamwork.git && cd automation-teamwork
            git checkout dev
            git pull origin dev
            docker-compose down
            docker-compose up -d --build